services:
  mysql-primary:
    image: mysql:8.0.42
    container_name: mysql-primary
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2fF2P7xqVtc4iCExR
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=appdb
      --binlog-do-db=db-mpp
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./primary-data:/var/lib/mysql
      - ./init/init-primary.sql:/docker-entrypoint-initdb.d/init.sql
      - ./primary-cnf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.10
    # Port tidak di-expose karena akses lewat ProxySQL

  mysql-replica:
    image: mysql:8.0.42
    container_name: mysql-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2fF2P7xqVtc4iCExR
    command: >
      --server-id=2
      --relay-log=relay-log
      --read-only=1
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./replicat-data:/var/lib/mysql
      - ./init/init-replica.sql:/docker-entrypoint-initdb.d/init.sql
      - ./replicat-cnf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.11
    depends_on:
      - mysql-primary

  proxysql:
    image: severalnines/proxysql:2.0
    container_name: proxysql
    ports:
      - "6033:6033"
      - "6032:6032"
      - "6080:6080"  # ProxySQL Web UI
    volumes:
      - ./proxysql/proxysql.cnf:/etc/proxysql.cnf
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.12
    depends_on:
      - mysql-primary
      - mysql-replica

  # ProxySQL Web Interface
  proxysql-web:
    image: proximacentauri/proxysql-web:latest
    container_name: proxysql-web
    ports:
      - "8080:8080"
    environment:
      - PROXYSQL_HOST=proxysql
      - PROXYSQL_PORT=6032
      - PROXYSQL_USERNAME=superman
      - PROXYSQL_PASSWORD=Soleh1!
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.15
    depends_on:
      - proxysql

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: proxysql
      PMA_PORT: 6033
      PMA_USER: appuser
      PMA_PASSWORD: AppPass123!
      UPLOAD_LIMIT: 1024M
    volumes:
      - ./phpmyadmin-config.inc.php:/etc/phpmyadmin/config.inc.php
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.16
    depends_on:
      - proxysql

  # Grafana for monitoring dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.17
    depends_on:
      - proxysql

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.18

  # MySQL Exporter for Prometheus
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=appuser:AppPass123!@(proxysql:6033)/
    networks:
      mysqlnet:
        ipv4_address: 172.20.0.19
    depends_on:
      - proxysql

networks:
  mysqlnet:
    name: mysqlnet
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  grafana-data:
  prometheus-data:
